# Generated by Django 5.2.7 on 2025-10-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='category',
            field=models.CharField(choices=[('AC Seater', 'AC Seater'), ('Non-AC Seater', 'Non-AC Seater'), ('AC Sleeper', 'AC Sleeper'), ('Non-AC Sleeper', 'Non-AC Sleeper')], default='Non-AC Seater', max_length=64),
        ),
        migrations.AddField(
            model_name='bus',
            name='travels_name',
            field=models.CharField(default='Unknown Travels', max_length=128),
        ),
    ]
