# Generated by Django 5.2.7 on 2025-10-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bus_category_bus_travels_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='category',
            field=models.CharField(choices=[('AC Seater', 'AC Seater'), ('Non-AC Seater', 'Non-AC Seater'), ('AC Sleeper', 'AC Sleeper'), ('Non-AC Sleeper', 'Non-AC Sleeper')], max_length=64),
        ),
        migrations.AlterField(
            model_name='bus',
            name='travels_name',
            field=models.CharField(max_length=128),
        ),
    ]
