# Generated by Django 5.2.7 on 2025-10-31 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_bus_category_alter_bus_travels_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='travel_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
