# Generated by Django 5.2.7 on 2025-11-01 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_bus_total_seats_alter_booking_table_and_more'),
    ]

    operations = [
    ]
