# Generated by Django 5.2.7 on 2025-11-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20251101_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'city',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='bus',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'managed': False},
        ),
    ]
