# Generated by Django 5.2.7 on 2025-11-02 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_city_alter_booking_options_alter_bus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={},
        ),
    ]
