# Generated by Django 5.2.7 on 2025-11-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_route_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'managed': False},
        ),
    ]
